// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers, omit_obvious_local_variable_types
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:robokassa_sdk/src/platform/messages.g.dart';

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is RkPaymentMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is RkPaymentOutcome) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is RkCredentialsMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is RkReceiptItemMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is RkReceiptMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is RkOrderMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is RkCustomerMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is RkViewMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is RkPaymentRequest) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is RkPaymentResultMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : RkPaymentMode.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : RkPaymentOutcome.values[value];
      case 131:
        return RkCredentialsMessage.decode(readValue(buffer)!);
      case 132:
        return RkReceiptItemMessage.decode(readValue(buffer)!);
      case 133:
        return RkReceiptMessage.decode(readValue(buffer)!);
      case 134:
        return RkOrderMessage.decode(readValue(buffer)!);
      case 135:
        return RkCustomerMessage.decode(readValue(buffer)!);
      case 136:
        return RkViewMessage.decode(readValue(buffer)!);
      case 137:
        return RkPaymentRequest.decode(readValue(buffer)!);
      case 138:
        return RkPaymentResultMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Operations implemented by the native Robokassa SDKs.
abstract class TestRobokassaHostApi {
  static TestDefaultBinaryMessengerBinding? get _testBinaryMessengerBinding =>
      TestDefaultBinaryMessengerBinding.instance;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Opens the native checkout screen and completes when it closes.
  Future<RkPaymentResultMessage> startPayment(RkPaymentRequest request);

  /// Captures a previously held payment.
  Future<bool> confirmHold(RkPaymentRequest request);

  /// Releases a previously held payment.
  Future<bool> cancelHold(RkPaymentRequest request);

  /// Charges a recurring payment against `order.previousInvoiceId`.
  Future<bool> chargeRecurring(RkPaymentRequest request);

  /// Queries the state of `order.invoiceId` without showing any UI.
  Future<RkPaymentResultMessage> checkPaymentState(RkPaymentRequest request);

  /// Whether the native Robokassa SDK is actually linked into this build.
  ///
  /// Lets an app fail with a useful message instead of a `ClassNotFound`
  /// crash when the consumer-side native setup was skipped.
  bool isNativeSdkAvailable();

  static void setUp(
    TestRobokassaHostApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.startPayment$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final RkPaymentRequest arg_request = args[0]! as RkPaymentRequest;
              try {
                final RkPaymentResultMessage output = await api.startPayment(
                  arg_request,
                );
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.confirmHold$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final RkPaymentRequest arg_request = args[0]! as RkPaymentRequest;
              try {
                final bool output = await api.confirmHold(arg_request);
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.cancelHold$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final RkPaymentRequest arg_request = args[0]! as RkPaymentRequest;
              try {
                final bool output = await api.cancelHold(arg_request);
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.chargeRecurring$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final RkPaymentRequest arg_request = args[0]! as RkPaymentRequest;
              try {
                final bool output = await api.chargeRecurring(arg_request);
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.checkPaymentState$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              final List<Object?> args = message! as List<Object?>;
              final RkPaymentRequest arg_request = args[0]! as RkPaymentRequest;
              try {
                final RkPaymentResultMessage output = await api
                    .checkPaymentState(arg_request);
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.isNativeSdkAvailable$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              try {
                final bool output = api.isNativeSdkAvailable();
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
  }
}
