// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Which checkout flow the native SDK should run.
enum RkPaymentMode: Int, CaseIterable {
  /// Ordinary one-stage payment.
  case simple = 0
  /// Two-stage payment: authorise and hold, capture later.
  case hold = 1
  /// First payment of a recurring series; the card is remembered.
  case recurrent = 2
  /// Payment reusing a card saved by an earlier operation (`token`).
  case savedCard = 3
}

/// How the native checkout screen finished.
enum RkPaymentOutcome: Int, CaseIterable {
  /// Payment reached a successful terminal state.
  case success = 0
  /// The user dismissed the checkout screen.
  case canceled = 1
  /// The flow failed; see `errorMessage`.
  case error = 2
}

/// Shop identity and passwords, as the native SDKs want them.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RkCredentialsMessage: Hashable, CustomStringConvertible {
  var merchantLogin: String
  var password1: String
  /// The native SDKs require password #2 on the device to poll payment state.
  var password2: String
  var isTest: Bool
  /// Success-redirect URL configured for the shop; the Android SDK watches for
  /// it to detect that checkout finished.
  var redirectUrl: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RkCredentialsMessage? {
    let merchantLogin = pigeonVar_list[0] as! String
    let password1 = pigeonVar_list[1] as! String
    let password2 = pigeonVar_list[2] as! String
    let isTest = pigeonVar_list[3] as! Bool
    let redirectUrl = pigeonVar_list[4] as! String

    return RkCredentialsMessage(
      merchantLogin: merchantLogin,
      password1: password1,
      password2: password2,
      isTest: isTest,
      redirectUrl: redirectUrl
    )
  }
  func toList() -> [Any?] {
    return [
      merchantLogin,
      password1,
      password2,
      isTest,
      redirectUrl,
    ]
  }
  static func == (lhs: RkCredentialsMessage, rhs: RkCredentialsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.merchantLogin, rhs.merchantLogin) && MessagesPigeonInternal.deepEquals(lhs.password1, rhs.password1) && MessagesPigeonInternal.deepEquals(lhs.password2, rhs.password2) && MessagesPigeonInternal.deepEquals(lhs.isTest, rhs.isTest) && MessagesPigeonInternal.deepEquals(lhs.redirectUrl, rhs.redirectUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RkCredentialsMessage")
    MessagesPigeonInternal.deepHash(value: merchantLogin, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: password1, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: password2, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isTest, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: redirectUrl, hasher: &hasher)
  }

  public var description: String {
    return "RkCredentialsMessage(merchantLogin: \(String(describing: merchantLogin)), password1: \(String(describing: password1)), password2: \(String(describing: password2)), isTest: \(String(describing: isTest)), redirectUrl: \(String(describing: redirectUrl)))"
  }
}

/// One fiscal receipt line.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RkReceiptItemMessage: Hashable, CustomStringConvertible {
  var name: String
  /// Integral quantities only — both native SDKs type this as `Int`.
  var quantity: Int64
  var sum: Double? = nil
  var cost: Double? = nil
  var nomenclatureCode: String? = nil
  /// `payment_method` wire value, e.g. `full_payment`.
  var paymentMethod: String? = nil
  /// `payment_object` wire value, e.g. `commodity`.
  var paymentObject: String? = nil
  /// `tax` wire value, e.g. `vat20`.
  var tax: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RkReceiptItemMessage? {
    let name = pigeonVar_list[0] as! String
    let quantity = pigeonVar_list[1] as! Int64
    let sum: Double? = nilOrValue(pigeonVar_list[2])
    let cost: Double? = nilOrValue(pigeonVar_list[3])
    let nomenclatureCode: String? = nilOrValue(pigeonVar_list[4])
    let paymentMethod: String? = nilOrValue(pigeonVar_list[5])
    let paymentObject: String? = nilOrValue(pigeonVar_list[6])
    let tax: String? = nilOrValue(pigeonVar_list[7])

    return RkReceiptItemMessage(
      name: name,
      quantity: quantity,
      sum: sum,
      cost: cost,
      nomenclatureCode: nomenclatureCode,
      paymentMethod: paymentMethod,
      paymentObject: paymentObject,
      tax: tax
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      quantity,
      sum,
      cost,
      nomenclatureCode,
      paymentMethod,
      paymentObject,
      tax,
    ]
  }
  static func == (lhs: RkReceiptItemMessage, rhs: RkReceiptItemMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.quantity, rhs.quantity) && MessagesPigeonInternal.deepEquals(lhs.sum, rhs.sum) && MessagesPigeonInternal.deepEquals(lhs.cost, rhs.cost) && MessagesPigeonInternal.deepEquals(lhs.nomenclatureCode, rhs.nomenclatureCode) && MessagesPigeonInternal.deepEquals(lhs.paymentMethod, rhs.paymentMethod) && MessagesPigeonInternal.deepEquals(lhs.paymentObject, rhs.paymentObject) && MessagesPigeonInternal.deepEquals(lhs.tax, rhs.tax)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RkReceiptItemMessage")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: quantity, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sum, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: cost, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nomenclatureCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: paymentMethod, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: paymentObject, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: tax, hasher: &hasher)
  }

  public var description: String {
    return "RkReceiptItemMessage(name: \(String(describing: name)), quantity: \(String(describing: quantity)), sum: \(String(describing: sum)), cost: \(String(describing: cost)), nomenclatureCode: \(String(describing: nomenclatureCode)), paymentMethod: \(String(describing: paymentMethod)), paymentObject: \(String(describing: paymentObject)), tax: \(String(describing: tax)))"
  }
}

/// Fiscal receipt attached to a payment.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RkReceiptMessage: Hashable, CustomStringConvertible {
  /// `sno` wire value, e.g. `usn_income`.
  var sno: String? = nil
  var items: [RkReceiptItemMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RkReceiptMessage? {
    let sno: String? = nilOrValue(pigeonVar_list[0])
    let items = pigeonVar_list[1] as! [RkReceiptItemMessage]

    return RkReceiptMessage(
      sno: sno,
      items: items
    )
  }
  func toList() -> [Any?] {
    return [
      sno,
      items,
    ]
  }
  static func == (lhs: RkReceiptMessage, rhs: RkReceiptMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sno, rhs.sno) && MessagesPigeonInternal.deepEquals(lhs.items, rhs.items)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RkReceiptMessage")
    MessagesPigeonInternal.deepHash(value: sno, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: items, hasher: &hasher)
  }

  public var description: String {
    return "RkReceiptMessage(sno: \(String(describing: sno)), items: \(String(describing: items)))"
  }
}

/// Order details.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RkOrderMessage: Hashable, CustomStringConvertible {
  var orderSum: Double
  var isRecurrent: Bool
  var isHold: Bool
  var invoiceId: Int64? = nil
  var previousInvoiceId: Int64? = nil
  /// `Description` — named `orderDescription` because Pigeon reserves
  /// `description` for Swift's `NSObject.description`.
  var orderDescription: String? = nil
  var incCurrLabel: String? = nil
  /// `OpKey` of the operation whose saved card should be charged.
  var token: String? = nil
  /// `OutSumCurrency` wire value, e.g. `USD`.
  var outSumCurrency: String? = nil
  /// `ExpirationDate` as milliseconds since the Unix epoch, UTC.
  var expirationDateEpochMs: Int64? = nil
  var receipt: RkReceiptMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RkOrderMessage? {
    let orderSum = pigeonVar_list[0] as! Double
    let isRecurrent = pigeonVar_list[1] as! Bool
    let isHold = pigeonVar_list[2] as! Bool
    let invoiceId: Int64? = nilOrValue(pigeonVar_list[3])
    let previousInvoiceId: Int64? = nilOrValue(pigeonVar_list[4])
    let orderDescription: String? = nilOrValue(pigeonVar_list[5])
    let incCurrLabel: String? = nilOrValue(pigeonVar_list[6])
    let token: String? = nilOrValue(pigeonVar_list[7])
    let outSumCurrency: String? = nilOrValue(pigeonVar_list[8])
    let expirationDateEpochMs: Int64? = nilOrValue(pigeonVar_list[9])
    let receipt: RkReceiptMessage? = nilOrValue(pigeonVar_list[10])

    return RkOrderMessage(
      orderSum: orderSum,
      isRecurrent: isRecurrent,
      isHold: isHold,
      invoiceId: invoiceId,
      previousInvoiceId: previousInvoiceId,
      orderDescription: orderDescription,
      incCurrLabel: incCurrLabel,
      token: token,
      outSumCurrency: outSumCurrency,
      expirationDateEpochMs: expirationDateEpochMs,
      receipt: receipt
    )
  }
  func toList() -> [Any?] {
    return [
      orderSum,
      isRecurrent,
      isHold,
      invoiceId,
      previousInvoiceId,
      orderDescription,
      incCurrLabel,
      token,
      outSumCurrency,
      expirationDateEpochMs,
      receipt,
    ]
  }
  static func == (lhs: RkOrderMessage, rhs: RkOrderMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.orderSum, rhs.orderSum) && MessagesPigeonInternal.deepEquals(lhs.isRecurrent, rhs.isRecurrent) && MessagesPigeonInternal.deepEquals(lhs.isHold, rhs.isHold) && MessagesPigeonInternal.deepEquals(lhs.invoiceId, rhs.invoiceId) && MessagesPigeonInternal.deepEquals(lhs.previousInvoiceId, rhs.previousInvoiceId) && MessagesPigeonInternal.deepEquals(lhs.orderDescription, rhs.orderDescription) && MessagesPigeonInternal.deepEquals(lhs.incCurrLabel, rhs.incCurrLabel) && MessagesPigeonInternal.deepEquals(lhs.token, rhs.token) && MessagesPigeonInternal.deepEquals(lhs.outSumCurrency, rhs.outSumCurrency) && MessagesPigeonInternal.deepEquals(lhs.expirationDateEpochMs, rhs.expirationDateEpochMs) && MessagesPigeonInternal.deepEquals(lhs.receipt, rhs.receipt)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RkOrderMessage")
    MessagesPigeonInternal.deepHash(value: orderSum, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isRecurrent, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isHold, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: invoiceId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: previousInvoiceId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: orderDescription, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: incCurrLabel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: token, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outSumCurrency, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: expirationDateEpochMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: receipt, hasher: &hasher)
  }

  public var description: String {
    return "RkOrderMessage(orderSum: \(String(describing: orderSum)), isRecurrent: \(String(describing: isRecurrent)), isHold: \(String(describing: isHold)), invoiceId: \(String(describing: invoiceId)), previousInvoiceId: \(String(describing: previousInvoiceId)), orderDescription: \(String(describing: orderDescription)), incCurrLabel: \(String(describing: incCurrLabel)), token: \(String(describing: token)), outSumCurrency: \(String(describing: outSumCurrency)), expirationDateEpochMs: \(String(describing: expirationDateEpochMs)), receipt: \(String(describing: receipt)))"
  }
}

/// Payer details.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RkCustomerMessage: Hashable, CustomStringConvertible {
  /// `Culture` wire value: `ru` or `en`.
  var culture: String? = nil
  var email: String? = nil
  var ip: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RkCustomerMessage? {
    let culture: String? = nilOrValue(pigeonVar_list[0])
    let email: String? = nilOrValue(pigeonVar_list[1])
    let ip: String? = nilOrValue(pigeonVar_list[2])

    return RkCustomerMessage(
      culture: culture,
      email: email,
      ip: ip
    )
  }
  func toList() -> [Any?] {
    return [
      culture,
      email,
      ip,
    ]
  }
  static func == (lhs: RkCustomerMessage, rhs: RkCustomerMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.culture, rhs.culture) && MessagesPigeonInternal.deepEquals(lhs.email, rhs.email) && MessagesPigeonInternal.deepEquals(lhs.ip, rhs.ip)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RkCustomerMessage")
    MessagesPigeonInternal.deepHash(value: culture, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: email, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ip, hasher: &hasher)
  }

  public var description: String {
    return "RkCustomerMessage(culture: \(String(describing: culture)), email: \(String(describing: email)), ip: \(String(describing: ip)))"
  }
}

/// Native checkout screen appearance.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RkViewMessage: Hashable, CustomStringConvertible {
  var hasToolbar: Bool
  var toolbarBgColor: String? = nil
  var toolbarTextColor: String? = nil
  var toolbarText: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RkViewMessage? {
    let hasToolbar = pigeonVar_list[0] as! Bool
    let toolbarBgColor: String? = nilOrValue(pigeonVar_list[1])
    let toolbarTextColor: String? = nilOrValue(pigeonVar_list[2])
    let toolbarText: String? = nilOrValue(pigeonVar_list[3])

    return RkViewMessage(
      hasToolbar: hasToolbar,
      toolbarBgColor: toolbarBgColor,
      toolbarTextColor: toolbarTextColor,
      toolbarText: toolbarText
    )
  }
  func toList() -> [Any?] {
    return [
      hasToolbar,
      toolbarBgColor,
      toolbarTextColor,
      toolbarText,
    ]
  }
  static func == (lhs: RkViewMessage, rhs: RkViewMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.hasToolbar, rhs.hasToolbar) && MessagesPigeonInternal.deepEquals(lhs.toolbarBgColor, rhs.toolbarBgColor) && MessagesPigeonInternal.deepEquals(lhs.toolbarTextColor, rhs.toolbarTextColor) && MessagesPigeonInternal.deepEquals(lhs.toolbarText, rhs.toolbarText)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RkViewMessage")
    MessagesPigeonInternal.deepHash(value: hasToolbar, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toolbarBgColor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toolbarTextColor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: toolbarText, hasher: &hasher)
  }

  public var description: String {
    return "RkViewMessage(hasToolbar: \(String(describing: hasToolbar)), toolbarBgColor: \(String(describing: toolbarBgColor)), toolbarTextColor: \(String(describing: toolbarTextColor)), toolbarText: \(String(describing: toolbarText)))"
  }
}

/// A complete native operation request.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RkPaymentRequest: Hashable, CustomStringConvertible {
  var mode: RkPaymentMode
  var credentials: RkCredentialsMessage
  var order: RkOrderMessage
  var customer: RkCustomerMessage
  var view: RkViewMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RkPaymentRequest? {
    let mode = pigeonVar_list[0] as! RkPaymentMode
    let credentials = pigeonVar_list[1] as! RkCredentialsMessage
    let order = pigeonVar_list[2] as! RkOrderMessage
    let customer = pigeonVar_list[3] as! RkCustomerMessage
    let view = pigeonVar_list[4] as! RkViewMessage

    return RkPaymentRequest(
      mode: mode,
      credentials: credentials,
      order: order,
      customer: customer,
      view: view
    )
  }
  func toList() -> [Any?] {
    return [
      mode,
      credentials,
      order,
      customer,
      view,
    ]
  }
  static func == (lhs: RkPaymentRequest, rhs: RkPaymentRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.mode, rhs.mode) && MessagesPigeonInternal.deepEquals(lhs.credentials, rhs.credentials) && MessagesPigeonInternal.deepEquals(lhs.order, rhs.order) && MessagesPigeonInternal.deepEquals(lhs.customer, rhs.customer) && MessagesPigeonInternal.deepEquals(lhs.view, rhs.view)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RkPaymentRequest")
    MessagesPigeonInternal.deepHash(value: mode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: credentials, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: order, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: customer, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: view, hasher: &hasher)
  }

  public var description: String {
    return "RkPaymentRequest(mode: \(String(describing: mode)), credentials: \(String(describing: credentials)), order: \(String(describing: order)), customer: \(String(describing: customer)), view: \(String(describing: view)))"
  }
}

/// Result of a native checkout screen.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RkPaymentResultMessage: Hashable, CustomStringConvertible {
  var outcome: RkPaymentOutcome
  var invoiceId: Int64? = nil
  /// Operation key — pass it back as `order.token` to charge the saved card.
  var opKey: String? = nil
  /// `<Result><Code>` value, e.g. `0`.
  var resultCode: String? = nil
  /// `<State><Code>` value, e.g. `100`.
  var stateCode: String? = nil
  /// Robokassa's own message, usually Russian. Named `stateDescription`
  /// because Pigeon reserves `description` for Swift's `NSObject.description`.
  var stateDescription: String? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RkPaymentResultMessage? {
    let outcome = pigeonVar_list[0] as! RkPaymentOutcome
    let invoiceId: Int64? = nilOrValue(pigeonVar_list[1])
    let opKey: String? = nilOrValue(pigeonVar_list[2])
    let resultCode: String? = nilOrValue(pigeonVar_list[3])
    let stateCode: String? = nilOrValue(pigeonVar_list[4])
    let stateDescription: String? = nilOrValue(pigeonVar_list[5])
    let errorMessage: String? = nilOrValue(pigeonVar_list[6])

    return RkPaymentResultMessage(
      outcome: outcome,
      invoiceId: invoiceId,
      opKey: opKey,
      resultCode: resultCode,
      stateCode: stateCode,
      stateDescription: stateDescription,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      outcome,
      invoiceId,
      opKey,
      resultCode,
      stateCode,
      stateDescription,
      errorMessage,
    ]
  }
  static func == (lhs: RkPaymentResultMessage, rhs: RkPaymentResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.outcome, rhs.outcome) && MessagesPigeonInternal.deepEquals(lhs.invoiceId, rhs.invoiceId) && MessagesPigeonInternal.deepEquals(lhs.opKey, rhs.opKey) && MessagesPigeonInternal.deepEquals(lhs.resultCode, rhs.resultCode) && MessagesPigeonInternal.deepEquals(lhs.stateCode, rhs.stateCode) && MessagesPigeonInternal.deepEquals(lhs.stateDescription, rhs.stateDescription) && MessagesPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RkPaymentResultMessage")
    MessagesPigeonInternal.deepHash(value: outcome, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: invoiceId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: opKey, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: resultCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stateCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stateDescription, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
  }

  public var description: String {
    return "RkPaymentResultMessage(outcome: \(String(describing: outcome)), invoiceId: \(String(describing: invoiceId)), opKey: \(String(describing: opKey)), resultCode: \(String(describing: resultCode)), stateCode: \(String(describing: stateCode)), stateDescription: \(String(describing: stateDescription)), errorMessage: \(String(describing: errorMessage)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RkPaymentMode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RkPaymentOutcome(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return RkCredentialsMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return RkReceiptItemMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return RkReceiptMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return RkOrderMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return RkCustomerMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return RkViewMessage.fromList(self.readValue() as! [Any?])
    case 137:
      return RkPaymentRequest.fromList(self.readValue() as! [Any?])
    case 138:
      return RkPaymentResultMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RkPaymentMode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? RkPaymentOutcome {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? RkCredentialsMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? RkReceiptItemMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? RkReceiptMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? RkOrderMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? RkCustomerMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? RkViewMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? RkPaymentRequest {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? RkPaymentResultMessage {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Operations implemented by the native Robokassa SDKs.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RobokassaHostApi {
  /// Opens the native checkout screen and completes when it closes.
  func startPayment(request: RkPaymentRequest, completion: @escaping (Result<RkPaymentResultMessage, Error>) -> Void)
  /// Captures a previously held payment.
  func confirmHold(request: RkPaymentRequest, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Releases a previously held payment.
  func cancelHold(request: RkPaymentRequest, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Charges a recurring payment against `order.previousInvoiceId`.
  func chargeRecurring(request: RkPaymentRequest, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Queries the state of `order.invoiceId` without showing any UI.
  func checkPaymentState(request: RkPaymentRequest, completion: @escaping (Result<RkPaymentResultMessage, Error>) -> Void)
  /// Whether the native Robokassa SDK is actually linked into this build.
  ///
  /// Lets an app fail with a useful message instead of a `ClassNotFound`
  /// crash when the consumer-side native setup was skipped.
  func isNativeSdkAvailable() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RobokassaHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `RobokassaHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RobokassaHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Opens the native checkout screen and completes when it closes.
    let startPaymentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.startPayment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startPaymentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RkPaymentRequest
        api.startPayment(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startPaymentChannel.setMessageHandler(nil)
    }
    /// Captures a previously held payment.
    let confirmHoldChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.confirmHold\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      confirmHoldChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RkPaymentRequest
        api.confirmHold(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      confirmHoldChannel.setMessageHandler(nil)
    }
    /// Releases a previously held payment.
    let cancelHoldChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.cancelHold\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelHoldChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RkPaymentRequest
        api.cancelHold(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelHoldChannel.setMessageHandler(nil)
    }
    /// Charges a recurring payment against `order.previousInvoiceId`.
    let chargeRecurringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.chargeRecurring\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      chargeRecurringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RkPaymentRequest
        api.chargeRecurring(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      chargeRecurringChannel.setMessageHandler(nil)
    }
    /// Queries the state of `order.invoiceId` without showing any UI.
    let checkPaymentStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.checkPaymentState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkPaymentStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RkPaymentRequest
        api.checkPaymentState(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkPaymentStateChannel.setMessageHandler(nil)
    }
    /// Whether the native Robokassa SDK is actually linked into this build.
    ///
    /// Lets an app fail with a useful message instead of a `ClassNotFound`
    /// crash when the consumer-side native setup was skipped.
    let isNativeSdkAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.isNativeSdkAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isNativeSdkAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isNativeSdkAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isNativeSdkAvailableChannel.setMessageHandler(nil)
    }
  }
}
