// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Which checkout flow the native SDK should run.
enum RkPaymentMode {
  /// Ordinary one-stage payment.
  simple,

  /// Two-stage payment: authorise and hold, capture later.
  hold,

  /// First payment of a recurring series; the card is remembered.
  recurrent,

  /// Payment reusing a card saved by an earlier operation (`token`).
  savedCard,
}

/// How the native checkout screen finished.
enum RkPaymentOutcome {
  /// Payment reached a successful terminal state.
  success,

  /// The user dismissed the checkout screen.
  canceled,

  /// The flow failed; see `errorMessage`.
  error,
}

/// Shop identity and passwords, as the native SDKs want them.
class RkCredentialsMessage {
  RkCredentialsMessage({
    required this.merchantLogin,
    required this.password1,
    required this.password2,
    required this.isTest,
    required this.redirectUrl,
  });

  String merchantLogin;

  String password1;

  /// The native SDKs require password #2 on the device to poll payment state.
  String password2;

  bool isTest;

  /// Success-redirect URL configured for the shop; the Android SDK watches for
  /// it to detect that checkout finished.
  String redirectUrl;

  List<Object?> _toList() {
    return <Object?>[merchantLogin, password1, password2, isTest, redirectUrl];
  }

  Object encode() {
    return _toList();
  }

  static RkCredentialsMessage decode(Object result) {
    result as List<Object?>;
    return RkCredentialsMessage(
      merchantLogin: result[0]! as String,
      password1: result[1]! as String,
      password2: result[2]! as String,
      isTest: result[3]! as bool,
      redirectUrl: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RkCredentialsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(merchantLogin, other.merchantLogin) &&
        _deepEquals(password1, other.password1) &&
        _deepEquals(password2, other.password2) &&
        _deepEquals(isTest, other.isTest) &&
        _deepEquals(redirectUrl, other.redirectUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RkCredentialsMessage(merchantLogin: $merchantLogin, password1: $password1, password2: $password2, isTest: $isTest, redirectUrl: $redirectUrl)';
  }
}

/// One fiscal receipt line.
class RkReceiptItemMessage {
  RkReceiptItemMessage({
    required this.name,
    required this.quantity,
    this.sum,
    this.cost,
    this.nomenclatureCode,
    this.paymentMethod,
    this.paymentObject,
    this.tax,
  });

  String name;

  /// Integral quantities only — both native SDKs type this as `Int`.
  int quantity;

  double? sum;

  double? cost;

  String? nomenclatureCode;

  /// `payment_method` wire value, e.g. `full_payment`.
  String? paymentMethod;

  /// `payment_object` wire value, e.g. `commodity`.
  String? paymentObject;

  /// `tax` wire value, e.g. `vat20`.
  String? tax;

  List<Object?> _toList() {
    return <Object?>[
      name,
      quantity,
      sum,
      cost,
      nomenclatureCode,
      paymentMethod,
      paymentObject,
      tax,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RkReceiptItemMessage decode(Object result) {
    result as List<Object?>;
    return RkReceiptItemMessage(
      name: result[0]! as String,
      quantity: result[1]! as int,
      sum: result[2] as double?,
      cost: result[3] as double?,
      nomenclatureCode: result[4] as String?,
      paymentMethod: result[5] as String?,
      paymentObject: result[6] as String?,
      tax: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RkReceiptItemMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(quantity, other.quantity) &&
        _deepEquals(sum, other.sum) &&
        _deepEquals(cost, other.cost) &&
        _deepEquals(nomenclatureCode, other.nomenclatureCode) &&
        _deepEquals(paymentMethod, other.paymentMethod) &&
        _deepEquals(paymentObject, other.paymentObject) &&
        _deepEquals(tax, other.tax);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RkReceiptItemMessage(name: $name, quantity: $quantity, sum: $sum, cost: $cost, nomenclatureCode: $nomenclatureCode, paymentMethod: $paymentMethod, paymentObject: $paymentObject, tax: $tax)';
  }
}

/// Fiscal receipt attached to a payment.
class RkReceiptMessage {
  RkReceiptMessage({this.sno, required this.items});

  /// `sno` wire value, e.g. `usn_income`.
  String? sno;

  List<RkReceiptItemMessage> items;

  List<Object?> _toList() {
    return <Object?>[sno, items];
  }

  Object encode() {
    return _toList();
  }

  static RkReceiptMessage decode(Object result) {
    result as List<Object?>;
    return RkReceiptMessage(
      sno: result[0] as String?,
      items: (result[1]! as List<Object?>).cast<RkReceiptItemMessage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RkReceiptMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sno, other.sno) && _deepEquals(items, other.items);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RkReceiptMessage(sno: $sno, items: $items)';
  }
}

/// Order details.
class RkOrderMessage {
  RkOrderMessage({
    required this.orderSum,
    required this.isRecurrent,
    required this.isHold,
    this.invoiceId,
    this.previousInvoiceId,
    this.orderDescription,
    this.incCurrLabel,
    this.token,
    this.outSumCurrency,
    this.expirationDateEpochMs,
    this.receipt,
  });

  double orderSum;

  bool isRecurrent;

  bool isHold;

  int? invoiceId;

  int? previousInvoiceId;

  /// `Description` — named `orderDescription` because Pigeon reserves
  /// `description` for Swift's `NSObject.description`.
  String? orderDescription;

  String? incCurrLabel;

  /// `OpKey` of the operation whose saved card should be charged.
  String? token;

  /// `OutSumCurrency` wire value, e.g. `USD`.
  String? outSumCurrency;

  /// `ExpirationDate` as milliseconds since the Unix epoch, UTC.
  int? expirationDateEpochMs;

  RkReceiptMessage? receipt;

  List<Object?> _toList() {
    return <Object?>[
      orderSum,
      isRecurrent,
      isHold,
      invoiceId,
      previousInvoiceId,
      orderDescription,
      incCurrLabel,
      token,
      outSumCurrency,
      expirationDateEpochMs,
      receipt,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RkOrderMessage decode(Object result) {
    result as List<Object?>;
    return RkOrderMessage(
      orderSum: result[0]! as double,
      isRecurrent: result[1]! as bool,
      isHold: result[2]! as bool,
      invoiceId: result[3] as int?,
      previousInvoiceId: result[4] as int?,
      orderDescription: result[5] as String?,
      incCurrLabel: result[6] as String?,
      token: result[7] as String?,
      outSumCurrency: result[8] as String?,
      expirationDateEpochMs: result[9] as int?,
      receipt: result[10] as RkReceiptMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RkOrderMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(orderSum, other.orderSum) &&
        _deepEquals(isRecurrent, other.isRecurrent) &&
        _deepEquals(isHold, other.isHold) &&
        _deepEquals(invoiceId, other.invoiceId) &&
        _deepEquals(previousInvoiceId, other.previousInvoiceId) &&
        _deepEquals(orderDescription, other.orderDescription) &&
        _deepEquals(incCurrLabel, other.incCurrLabel) &&
        _deepEquals(token, other.token) &&
        _deepEquals(outSumCurrency, other.outSumCurrency) &&
        _deepEquals(expirationDateEpochMs, other.expirationDateEpochMs) &&
        _deepEquals(receipt, other.receipt);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RkOrderMessage(orderSum: $orderSum, isRecurrent: $isRecurrent, isHold: $isHold, invoiceId: $invoiceId, previousInvoiceId: $previousInvoiceId, orderDescription: $orderDescription, incCurrLabel: $incCurrLabel, token: $token, outSumCurrency: $outSumCurrency, expirationDateEpochMs: $expirationDateEpochMs, receipt: $receipt)';
  }
}

/// Payer details.
class RkCustomerMessage {
  RkCustomerMessage({this.culture, this.email, this.ip});

  /// `Culture` wire value: `ru` or `en`.
  String? culture;

  String? email;

  String? ip;

  List<Object?> _toList() {
    return <Object?>[culture, email, ip];
  }

  Object encode() {
    return _toList();
  }

  static RkCustomerMessage decode(Object result) {
    result as List<Object?>;
    return RkCustomerMessage(
      culture: result[0] as String?,
      email: result[1] as String?,
      ip: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RkCustomerMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(culture, other.culture) &&
        _deepEquals(email, other.email) &&
        _deepEquals(ip, other.ip);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RkCustomerMessage(culture: $culture, email: $email, ip: $ip)';
  }
}

/// Native checkout screen appearance.
class RkViewMessage {
  RkViewMessage({
    required this.hasToolbar,
    this.toolbarBgColor,
    this.toolbarTextColor,
    this.toolbarText,
  });

  bool hasToolbar;

  String? toolbarBgColor;

  String? toolbarTextColor;

  String? toolbarText;

  List<Object?> _toList() {
    return <Object?>[hasToolbar, toolbarBgColor, toolbarTextColor, toolbarText];
  }

  Object encode() {
    return _toList();
  }

  static RkViewMessage decode(Object result) {
    result as List<Object?>;
    return RkViewMessage(
      hasToolbar: result[0]! as bool,
      toolbarBgColor: result[1] as String?,
      toolbarTextColor: result[2] as String?,
      toolbarText: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RkViewMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hasToolbar, other.hasToolbar) &&
        _deepEquals(toolbarBgColor, other.toolbarBgColor) &&
        _deepEquals(toolbarTextColor, other.toolbarTextColor) &&
        _deepEquals(toolbarText, other.toolbarText);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RkViewMessage(hasToolbar: $hasToolbar, toolbarBgColor: $toolbarBgColor, toolbarTextColor: $toolbarTextColor, toolbarText: $toolbarText)';
  }
}

/// A complete native operation request.
class RkPaymentRequest {
  RkPaymentRequest({
    required this.mode,
    required this.credentials,
    required this.order,
    required this.customer,
    required this.view,
  });

  RkPaymentMode mode;

  RkCredentialsMessage credentials;

  RkOrderMessage order;

  RkCustomerMessage customer;

  RkViewMessage view;

  List<Object?> _toList() {
    return <Object?>[mode, credentials, order, customer, view];
  }

  Object encode() {
    return _toList();
  }

  static RkPaymentRequest decode(Object result) {
    result as List<Object?>;
    return RkPaymentRequest(
      mode: result[0]! as RkPaymentMode,
      credentials: result[1]! as RkCredentialsMessage,
      order: result[2]! as RkOrderMessage,
      customer: result[3]! as RkCustomerMessage,
      view: result[4]! as RkViewMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RkPaymentRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mode, other.mode) &&
        _deepEquals(credentials, other.credentials) &&
        _deepEquals(order, other.order) &&
        _deepEquals(customer, other.customer) &&
        _deepEquals(view, other.view);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RkPaymentRequest(mode: $mode, credentials: $credentials, order: $order, customer: $customer, view: $view)';
  }
}

/// Result of a native checkout screen.
class RkPaymentResultMessage {
  RkPaymentResultMessage({
    required this.outcome,
    this.invoiceId,
    this.opKey,
    this.resultCode,
    this.stateCode,
    this.stateDescription,
    this.errorMessage,
  });

  RkPaymentOutcome outcome;

  int? invoiceId;

  /// Operation key — pass it back as `order.token` to charge the saved card.
  String? opKey;

  /// `<Result><Code>` value, e.g. `0`.
  String? resultCode;

  /// `<State><Code>` value, e.g. `100`.
  String? stateCode;

  /// Robokassa's own message, usually Russian. Named `stateDescription`
  /// because Pigeon reserves `description` for Swift's `NSObject.description`.
  String? stateDescription;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      outcome,
      invoiceId,
      opKey,
      resultCode,
      stateCode,
      stateDescription,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RkPaymentResultMessage decode(Object result) {
    result as List<Object?>;
    return RkPaymentResultMessage(
      outcome: result[0]! as RkPaymentOutcome,
      invoiceId: result[1] as int?,
      opKey: result[2] as String?,
      resultCode: result[3] as String?,
      stateCode: result[4] as String?,
      stateDescription: result[5] as String?,
      errorMessage: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RkPaymentResultMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outcome, other.outcome) &&
        _deepEquals(invoiceId, other.invoiceId) &&
        _deepEquals(opKey, other.opKey) &&
        _deepEquals(resultCode, other.resultCode) &&
        _deepEquals(stateCode, other.stateCode) &&
        _deepEquals(stateDescription, other.stateDescription) &&
        _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RkPaymentResultMessage(outcome: $outcome, invoiceId: $invoiceId, opKey: $opKey, resultCode: $resultCode, stateCode: $stateCode, stateDescription: $stateDescription, errorMessage: $errorMessage)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is RkPaymentMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is RkPaymentOutcome) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is RkCredentialsMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is RkReceiptItemMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is RkReceiptMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is RkOrderMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is RkCustomerMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is RkViewMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is RkPaymentRequest) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is RkPaymentResultMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : RkPaymentMode.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : RkPaymentOutcome.values[value];
      case 131:
        return RkCredentialsMessage.decode(readValue(buffer)!);
      case 132:
        return RkReceiptItemMessage.decode(readValue(buffer)!);
      case 133:
        return RkReceiptMessage.decode(readValue(buffer)!);
      case 134:
        return RkOrderMessage.decode(readValue(buffer)!);
      case 135:
        return RkCustomerMessage.decode(readValue(buffer)!);
      case 136:
        return RkViewMessage.decode(readValue(buffer)!);
      case 137:
        return RkPaymentRequest.decode(readValue(buffer)!);
      case 138:
        return RkPaymentResultMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Operations implemented by the native Robokassa SDKs.
class RobokassaHostApi {
  /// Constructor for [RobokassaHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RobokassaHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Opens the native checkout screen and completes when it closes.
  Future<RkPaymentResultMessage> startPayment(RkPaymentRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.startPayment$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as RkPaymentResultMessage;
  }

  /// Captures a previously held payment.
  Future<bool> confirmHold(RkPaymentRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.confirmHold$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Releases a previously held payment.
  Future<bool> cancelHold(RkPaymentRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.cancelHold$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Charges a recurring payment against `order.previousInvoiceId`.
  Future<bool> chargeRecurring(RkPaymentRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.chargeRecurring$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Queries the state of `order.invoiceId` without showing any UI.
  Future<RkPaymentResultMessage> checkPaymentState(
    RkPaymentRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.checkPaymentState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as RkPaymentResultMessage;
  }

  /// Whether the native Robokassa SDK is actually linked into this build.
  ///
  /// Lets an app fail with a useful message instead of a `ClassNotFound`
  /// crash when the consumer-side native setup was skipped.
  Future<bool> isNativeSdkAvailable() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.isNativeSdkAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
