// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package ru.robokassa.robokassa_sdk

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Which checkout flow the native SDK should run. */
enum class RkPaymentMode(val raw: Int) {
  /** Ordinary one-stage payment. */
  SIMPLE(0),
  /** Two-stage payment: authorise and hold, capture later. */
  HOLD(1),
  /** First payment of a recurring series; the card is remembered. */
  RECURRENT(2),
  /** Payment reusing a card saved by an earlier operation (`token`). */
  SAVED_CARD(3);

  companion object {
    fun ofRaw(raw: Int): RkPaymentMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** How the native checkout screen finished. */
enum class RkPaymentOutcome(val raw: Int) {
  /** Payment reached a successful terminal state. */
  SUCCESS(0),
  /** The user dismissed the checkout screen. */
  CANCELED(1),
  /** The flow failed; see `errorMessage`. */
  ERROR(2);

  companion object {
    fun ofRaw(raw: Int): RkPaymentOutcome? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Shop identity and passwords, as the native SDKs want them.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RkCredentialsMessage (
  val merchantLogin: String,
  val password1: String,
  /** The native SDKs require password #2 on the device to poll payment state. */
  val password2: String,
  val isTest: Boolean,
  /**
   * Success-redirect URL configured for the shop; the Android SDK watches for
   * it to detect that checkout finished.
   */
  val redirectUrl: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RkCredentialsMessage {
      val merchantLogin = pigeonVar_list[0] as String
      val password1 = pigeonVar_list[1] as String
      val password2 = pigeonVar_list[2] as String
      val isTest = pigeonVar_list[3] as Boolean
      val redirectUrl = pigeonVar_list[4] as String
      return RkCredentialsMessage(merchantLogin, password1, password2, isTest, redirectUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      merchantLogin,
      password1,
      password2,
      isTest,
      redirectUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RkCredentialsMessage
    return MessagesPigeonUtils.deepEquals(this.merchantLogin, other.merchantLogin) && MessagesPigeonUtils.deepEquals(this.password1, other.password1) && MessagesPigeonUtils.deepEquals(this.password2, other.password2) && MessagesPigeonUtils.deepEquals(this.isTest, other.isTest) && MessagesPigeonUtils.deepEquals(this.redirectUrl, other.redirectUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.merchantLogin)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.password1)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.password2)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isTest)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.redirectUrl)
    return result
  }
  override fun toString(): String {
    return "RkCredentialsMessage(merchantLogin=$merchantLogin, password1=$password1, password2=$password2, isTest=$isTest, redirectUrl=$redirectUrl)"
  }
}

/**
 * One fiscal receipt line.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RkReceiptItemMessage (
  val name: String,
  /** Integral quantities only — both native SDKs type this as `Int`. */
  val quantity: Long,
  val sum: Double? = null,
  val cost: Double? = null,
  val nomenclatureCode: String? = null,
  /** `payment_method` wire value, e.g. `full_payment`. */
  val paymentMethod: String? = null,
  /** `payment_object` wire value, e.g. `commodity`. */
  val paymentObject: String? = null,
  /** `tax` wire value, e.g. `vat20`. */
  val tax: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RkReceiptItemMessage {
      val name = pigeonVar_list[0] as String
      val quantity = pigeonVar_list[1] as Long
      val sum = pigeonVar_list[2] as Double?
      val cost = pigeonVar_list[3] as Double?
      val nomenclatureCode = pigeonVar_list[4] as String?
      val paymentMethod = pigeonVar_list[5] as String?
      val paymentObject = pigeonVar_list[6] as String?
      val tax = pigeonVar_list[7] as String?
      return RkReceiptItemMessage(name, quantity, sum, cost, nomenclatureCode, paymentMethod, paymentObject, tax)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      quantity,
      sum,
      cost,
      nomenclatureCode,
      paymentMethod,
      paymentObject,
      tax,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RkReceiptItemMessage
    return MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.quantity, other.quantity) && MessagesPigeonUtils.deepEquals(this.sum, other.sum) && MessagesPigeonUtils.deepEquals(this.cost, other.cost) && MessagesPigeonUtils.deepEquals(this.nomenclatureCode, other.nomenclatureCode) && MessagesPigeonUtils.deepEquals(this.paymentMethod, other.paymentMethod) && MessagesPigeonUtils.deepEquals(this.paymentObject, other.paymentObject) && MessagesPigeonUtils.deepEquals(this.tax, other.tax)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.quantity)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sum)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cost)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nomenclatureCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.paymentMethod)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.paymentObject)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tax)
    return result
  }
  override fun toString(): String {
    return "RkReceiptItemMessage(name=$name, quantity=$quantity, sum=$sum, cost=$cost, nomenclatureCode=$nomenclatureCode, paymentMethod=$paymentMethod, paymentObject=$paymentObject, tax=$tax)"
  }
}

/**
 * Fiscal receipt attached to a payment.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RkReceiptMessage (
  /** `sno` wire value, e.g. `usn_income`. */
  val sno: String? = null,
  val items: List<RkReceiptItemMessage>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RkReceiptMessage {
      val sno = pigeonVar_list[0] as String?
      val items = pigeonVar_list[1] as List<RkReceiptItemMessage>
      return RkReceiptMessage(sno, items)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sno,
      items,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RkReceiptMessage
    return MessagesPigeonUtils.deepEquals(this.sno, other.sno) && MessagesPigeonUtils.deepEquals(this.items, other.items)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sno)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.items)
    return result
  }
  override fun toString(): String {
    return "RkReceiptMessage(sno=$sno, items=$items)"
  }
}

/**
 * Order details.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RkOrderMessage (
  val orderSum: Double,
  val isRecurrent: Boolean,
  val isHold: Boolean,
  val invoiceId: Long? = null,
  val previousInvoiceId: Long? = null,
  /**
   * `Description` — named `orderDescription` because Pigeon reserves
   * `description` for Swift's `NSObject.description`.
   */
  val orderDescription: String? = null,
  val incCurrLabel: String? = null,
  /** `OpKey` of the operation whose saved card should be charged. */
  val token: String? = null,
  /** `OutSumCurrency` wire value, e.g. `USD`. */
  val outSumCurrency: String? = null,
  /** `ExpirationDate` as milliseconds since the Unix epoch, UTC. */
  val expirationDateEpochMs: Long? = null,
  val receipt: RkReceiptMessage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RkOrderMessage {
      val orderSum = pigeonVar_list[0] as Double
      val isRecurrent = pigeonVar_list[1] as Boolean
      val isHold = pigeonVar_list[2] as Boolean
      val invoiceId = pigeonVar_list[3] as Long?
      val previousInvoiceId = pigeonVar_list[4] as Long?
      val orderDescription = pigeonVar_list[5] as String?
      val incCurrLabel = pigeonVar_list[6] as String?
      val token = pigeonVar_list[7] as String?
      val outSumCurrency = pigeonVar_list[8] as String?
      val expirationDateEpochMs = pigeonVar_list[9] as Long?
      val receipt = pigeonVar_list[10] as RkReceiptMessage?
      return RkOrderMessage(orderSum, isRecurrent, isHold, invoiceId, previousInvoiceId, orderDescription, incCurrLabel, token, outSumCurrency, expirationDateEpochMs, receipt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      orderSum,
      isRecurrent,
      isHold,
      invoiceId,
      previousInvoiceId,
      orderDescription,
      incCurrLabel,
      token,
      outSumCurrency,
      expirationDateEpochMs,
      receipt,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RkOrderMessage
    return MessagesPigeonUtils.deepEquals(this.orderSum, other.orderSum) && MessagesPigeonUtils.deepEquals(this.isRecurrent, other.isRecurrent) && MessagesPigeonUtils.deepEquals(this.isHold, other.isHold) && MessagesPigeonUtils.deepEquals(this.invoiceId, other.invoiceId) && MessagesPigeonUtils.deepEquals(this.previousInvoiceId, other.previousInvoiceId) && MessagesPigeonUtils.deepEquals(this.orderDescription, other.orderDescription) && MessagesPigeonUtils.deepEquals(this.incCurrLabel, other.incCurrLabel) && MessagesPigeonUtils.deepEquals(this.token, other.token) && MessagesPigeonUtils.deepEquals(this.outSumCurrency, other.outSumCurrency) && MessagesPigeonUtils.deepEquals(this.expirationDateEpochMs, other.expirationDateEpochMs) && MessagesPigeonUtils.deepEquals(this.receipt, other.receipt)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.orderSum)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isRecurrent)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isHold)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.invoiceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.previousInvoiceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.orderDescription)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.incCurrLabel)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.token)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outSumCurrency)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.expirationDateEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.receipt)
    return result
  }
  override fun toString(): String {
    return "RkOrderMessage(orderSum=$orderSum, isRecurrent=$isRecurrent, isHold=$isHold, invoiceId=$invoiceId, previousInvoiceId=$previousInvoiceId, orderDescription=$orderDescription, incCurrLabel=$incCurrLabel, token=$token, outSumCurrency=$outSumCurrency, expirationDateEpochMs=$expirationDateEpochMs, receipt=$receipt)"
  }
}

/**
 * Payer details.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RkCustomerMessage (
  /** `Culture` wire value: `ru` or `en`. */
  val culture: String? = null,
  val email: String? = null,
  val ip: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RkCustomerMessage {
      val culture = pigeonVar_list[0] as String?
      val email = pigeonVar_list[1] as String?
      val ip = pigeonVar_list[2] as String?
      return RkCustomerMessage(culture, email, ip)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      culture,
      email,
      ip,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RkCustomerMessage
    return MessagesPigeonUtils.deepEquals(this.culture, other.culture) && MessagesPigeonUtils.deepEquals(this.email, other.email) && MessagesPigeonUtils.deepEquals(this.ip, other.ip)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.culture)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.email)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ip)
    return result
  }
  override fun toString(): String {
    return "RkCustomerMessage(culture=$culture, email=$email, ip=$ip)"
  }
}

/**
 * Native checkout screen appearance.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RkViewMessage (
  val hasToolbar: Boolean,
  val toolbarBgColor: String? = null,
  val toolbarTextColor: String? = null,
  val toolbarText: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RkViewMessage {
      val hasToolbar = pigeonVar_list[0] as Boolean
      val toolbarBgColor = pigeonVar_list[1] as String?
      val toolbarTextColor = pigeonVar_list[2] as String?
      val toolbarText = pigeonVar_list[3] as String?
      return RkViewMessage(hasToolbar, toolbarBgColor, toolbarTextColor, toolbarText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      hasToolbar,
      toolbarBgColor,
      toolbarTextColor,
      toolbarText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RkViewMessage
    return MessagesPigeonUtils.deepEquals(this.hasToolbar, other.hasToolbar) && MessagesPigeonUtils.deepEquals(this.toolbarBgColor, other.toolbarBgColor) && MessagesPigeonUtils.deepEquals(this.toolbarTextColor, other.toolbarTextColor) && MessagesPigeonUtils.deepEquals(this.toolbarText, other.toolbarText)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasToolbar)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.toolbarBgColor)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.toolbarTextColor)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.toolbarText)
    return result
  }
  override fun toString(): String {
    return "RkViewMessage(hasToolbar=$hasToolbar, toolbarBgColor=$toolbarBgColor, toolbarTextColor=$toolbarTextColor, toolbarText=$toolbarText)"
  }
}

/**
 * A complete native operation request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RkPaymentRequest (
  val mode: RkPaymentMode,
  val credentials: RkCredentialsMessage,
  val order: RkOrderMessage,
  val customer: RkCustomerMessage,
  val view: RkViewMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RkPaymentRequest {
      val mode = pigeonVar_list[0] as RkPaymentMode
      val credentials = pigeonVar_list[1] as RkCredentialsMessage
      val order = pigeonVar_list[2] as RkOrderMessage
      val customer = pigeonVar_list[3] as RkCustomerMessage
      val view = pigeonVar_list[4] as RkViewMessage
      return RkPaymentRequest(mode, credentials, order, customer, view)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mode,
      credentials,
      order,
      customer,
      view,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RkPaymentRequest
    return MessagesPigeonUtils.deepEquals(this.mode, other.mode) && MessagesPigeonUtils.deepEquals(this.credentials, other.credentials) && MessagesPigeonUtils.deepEquals(this.order, other.order) && MessagesPigeonUtils.deepEquals(this.customer, other.customer) && MessagesPigeonUtils.deepEquals(this.view, other.view)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.credentials)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.order)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.customer)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.view)
    return result
  }
  override fun toString(): String {
    return "RkPaymentRequest(mode=$mode, credentials=$credentials, order=$order, customer=$customer, view=$view)"
  }
}

/**
 * Result of a native checkout screen.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RkPaymentResultMessage (
  val outcome: RkPaymentOutcome,
  val invoiceId: Long? = null,
  /** Operation key — pass it back as `order.token` to charge the saved card. */
  val opKey: String? = null,
  /** `<Result><Code>` value, e.g. `0`. */
  val resultCode: String? = null,
  /** `<State><Code>` value, e.g. `100`. */
  val stateCode: String? = null,
  /**
   * Robokassa's own message, usually Russian. Named `stateDescription`
   * because Pigeon reserves `description` for Swift's `NSObject.description`.
   */
  val stateDescription: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RkPaymentResultMessage {
      val outcome = pigeonVar_list[0] as RkPaymentOutcome
      val invoiceId = pigeonVar_list[1] as Long?
      val opKey = pigeonVar_list[2] as String?
      val resultCode = pigeonVar_list[3] as String?
      val stateCode = pigeonVar_list[4] as String?
      val stateDescription = pigeonVar_list[5] as String?
      val errorMessage = pigeonVar_list[6] as String?
      return RkPaymentResultMessage(outcome, invoiceId, opKey, resultCode, stateCode, stateDescription, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      outcome,
      invoiceId,
      opKey,
      resultCode,
      stateCode,
      stateDescription,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RkPaymentResultMessage
    return MessagesPigeonUtils.deepEquals(this.outcome, other.outcome) && MessagesPigeonUtils.deepEquals(this.invoiceId, other.invoiceId) && MessagesPigeonUtils.deepEquals(this.opKey, other.opKey) && MessagesPigeonUtils.deepEquals(this.resultCode, other.resultCode) && MessagesPigeonUtils.deepEquals(this.stateCode, other.stateCode) && MessagesPigeonUtils.deepEquals(this.stateDescription, other.stateDescription) && MessagesPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outcome)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.invoiceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.opKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.resultCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.stateCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.stateDescription)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "RkPaymentResultMessage(outcome=$outcome, invoiceId=$invoiceId, opKey=$opKey, resultCode=$resultCode, stateCode=$stateCode, stateDescription=$stateDescription, errorMessage=$errorMessage)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RkPaymentMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RkPaymentOutcome.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RkCredentialsMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RkReceiptItemMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RkReceiptMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RkOrderMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RkCustomerMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RkViewMessage.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RkPaymentRequest.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RkPaymentResultMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RkPaymentMode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is RkPaymentOutcome -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is RkCredentialsMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RkReceiptItemMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is RkReceiptMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is RkOrderMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is RkCustomerMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is RkViewMessage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is RkPaymentRequest -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is RkPaymentResultMessage -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Operations implemented by the native Robokassa SDKs.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface RobokassaHostApi {
  /** Opens the native checkout screen and completes when it closes. */
  fun startPayment(request: RkPaymentRequest, callback: (Result<RkPaymentResultMessage>) -> Unit)
  /** Captures a previously held payment. */
  fun confirmHold(request: RkPaymentRequest, callback: (Result<Boolean>) -> Unit)
  /** Releases a previously held payment. */
  fun cancelHold(request: RkPaymentRequest, callback: (Result<Boolean>) -> Unit)
  /** Charges a recurring payment against `order.previousInvoiceId`. */
  fun chargeRecurring(request: RkPaymentRequest, callback: (Result<Boolean>) -> Unit)
  /** Queries the state of `order.invoiceId` without showing any UI. */
  fun checkPaymentState(request: RkPaymentRequest, callback: (Result<RkPaymentResultMessage>) -> Unit)
  /**
   * Whether the native Robokassa SDK is actually linked into this build.
   *
   * Lets an app fail with a useful message instead of a `ClassNotFound`
   * crash when the consumer-side native setup was skipped.
   */
  fun isNativeSdkAvailable(): Boolean

  companion object {
    /** The codec used by RobokassaHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `RobokassaHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RobokassaHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.startPayment$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RkPaymentRequest
            api.startPayment(requestArg) { result: Result<RkPaymentResultMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.confirmHold$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RkPaymentRequest
            api.confirmHold(requestArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.cancelHold$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RkPaymentRequest
            api.cancelHold(requestArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.chargeRecurring$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RkPaymentRequest
            api.chargeRecurring(requestArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.checkPaymentState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RkPaymentRequest
            api.checkPaymentState(requestArg) { result: Result<RkPaymentResultMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.robokassa_sdk.RobokassaHostApi.isNativeSdkAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isNativeSdkAvailable())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
